import { Product } from './app.interface';
export const PRODUCTS: Product[] = [
	{
		name: 'Rose',
		id: 'rose',
		category: 'Essence Collection',
		images: [
			'assets/photo/rose/1.jpg',
			'assets/photo/rose/2.jpg',
			'assets/photo/rose/3.jpg',
			'assets/photo/rose/4.jpg',
			'assets/photo/rose/5.jpg',
			'assets/photo/rose/6.jpg',
			'assets/photo/rose/7.jpg',
			'assets/photo/rose/8.jpg',
		],
		description: {
			en: 'Rose is a transformative gown featuring a structured, fitted corset adorned with pearls, clearly defining the waist. The skirt follows the hips before softly flaring out, creating a confident, sculpted silhouette. A pearl necklace detail at the neckline completes the look with a classic, refined finish.',
			ua: 'Rose — сукня-трансформер зі структурованим приталеним корсетом, прикрашеним перлами, що чітко підкреслює талію. Спідниця щільно облягає стегна та плавно розширюється донизу, формуючи виразний силует. Перлинний декор у зоні декольте завершує образ стриманою класикою.',
		},
	},
	{
		name: 'Felix',
		id: 'felix',
		category: 'Signature Collection',
		images: [
			'assets/photo/felix/1.jpg',
			'assets/photo/felix/2.jpg',
			'assets/photo/felix/3.jpg',
			'assets/photo/felix/4.jpg',
			'assets/photo/felix/5.jpg',
		],
		description: {
			en: "The 'Felix' gown is understated and refined, with a soft, voluminous skirt adorned with floral and leafy lace. The fitted bodice enhances the silhouette and features the same delicate lace. An open neckline brings a hint of romance, while a row of buttons along the back adds a timeless touch. A perfect choice for the bride who values subtle elegance and lightness in every detail.",
			ua: "Сукня 'Felix' — лаконічна та витончена, з легкою об’ємною спідницею, прикрашеною мереживом із квітами та листям. Щільний корсет підкреслює силует і оздоблений таким самим ніжним мереживом. Відкрите декольте додає романтики, а ряд гудзиків на спинці — класичного шарму. Ідеальний вибір для нареченої, яка цінує стриману елегантність і легкість у кожній деталі.",
		},
	},
	{
		name: 'Lea',
		id: 'lea',
		category: 'Signature Collection',
		images: [
			'assets/photo/lea/1.jpg',
			'assets/photo/lea/2.jpg',
			'assets/photo/lea/3.jpg',
			'assets/photo/lea/4.jpg',
			'assets/photo/lea/5.jpg',
		],
		description: {
			en: "The 'Lea' dress is a timeless and romantic gown that embodies elegance and grace. Its strapless ruched bodice beautifully shapes the figure, while the flowing tulle skirt creates a soft and airy look. The corset back ensures a perfect fit, enhancing both comfort and style. This dress is perfect for brides who appreciate classic beauty with a modern touch.",
			ua: "Сукня 'Lea' — це вічна класика та романтичний образ, що випромінює елегантність і ніжність. Корсетний ліф із драпіруванням чудово підкреслює фігуру, а легка фатинова спідниця надає легкості та витонченості. Завдяки корсетній спинці сукня ідеально сідає, забезпечуючи комфорт і стиль. Ідеальний вибір для наречених, які цінують класичну красу з сучасним акцентом.",
		},
	},
	{
		name: 'Jeanne',
		id: 'jeanne',
		category: 'Essence Collection',
		images: [
			'assets/photo/jeanne/1.jpg',
			'assets/photo/jeanne/2.jpg',
			'assets/photo/jeanne/3.jpg',
			'assets/photo/jeanne/4.jpg',
			'assets/photo/jeanne/5.jpg',
			'assets/photo/jeanne/6.jpg',
		],
		description: {
			en: 'Jeanne is crafted from flesh-toned fabric and finished with iconic French Chantilly lace. The corset features adjustable back ties for a refined fit that softly follows the body, while the delicate neckline keeps the look elegant and balanced. A timeless choice for brides who appreciate subtle detail and classic craftsmanship.',
			ua: 'Jeanne виготовлена з тканини тілесного відтінку та оздоблена легендарним французьким мереживом Chantilly. Корсет зі шнурівкою на спинці дозволяє точно підкреслити фігуру, а делікатна лінія декольте додає образу витонченості. Класичний вибір для наречених, які цінують стриману елегантність.',
		},
	},
	{
		name: 'Doris',
		id: 'doris',
		category: 'Signature Collection',
		images: [
			'assets/photo/doris/1.jpg',
			'assets/photo/doris/2.jpg',
			'assets/photo/doris/3.jpg',
			'assets/photo/doris/4.jpg',
			'assets/photo/doris/5.jpg',
		],
		description: {
			en: "The 'Doris' gown is an elegant strapless wedding dress with a soft A-line silhouette and modern details. Crafted from airy tulle and adorned with intricate floral and leafy embroidery, the dress exudes lightness and grace. The structured bodice flatters the figure with subtle transparency, while the sweetheart neckline adds romantic charm. A high slit offers a bold yet tasteful touch, and a delicate row of buttons at the back completes the look with classic refinement.",
			ua: "Сукня 'Doris' — це елегантна весільна сукня без бретелей з м’яким А-силуетом і сучасними акцентами. Виготовлена з легкої фатинової тканини, оздоблена вишуканою вишивкою у вигляді квітів і листя, вона випромінює ніжність і витонченість. Щільний корсет із ледь помітною прозорістю підкреслює фігуру, а виріз серця додає образу романтики. Високий розріз на спідниці надає сміливого штриха, а ряд делікатних ґудзиків на спинці завершує образ класичною елегантністю.",
		},
	},
	{
		name: 'Gaby',
		id: 'gaby',
		category: 'Signature Collection',
		images: [
			'assets/photo/gaby/1.jpg',
			'assets/photo/gaby/2.jpg',
			'assets/photo/gaby/3.jpg',
			'assets/photo/gaby/4.jpg',
			'assets/photo/gaby/5.jpg',
		],
		description: {
			en: "The 'Gaby' dress is a timeless transformer wedding gown crafted from luxurious satin. Featuring a structured draped corset and a romantic sweetheart neckline, this gown is designed to accentuate the bride’s silhouette. The highlight of the look is its voluminous detachable sleeves, which create an elegant off-shoulder effect for the ceremony. Remove the sleeves to reveal a refined strapless silhouette, perfect for dancing the night away. A high slit adds a touch of modern allure to this classic design, allowing for effortless movement and two distinct bridal looks in one.",
			ua: "Сукня 'Gaby' — це вічна класика у стилі трансформер, виконана з розкішного сатину. Структурований драпірований корсет і романтичне декольте-сердечко створюють витончений силует. Особливістю образу є об’ємні знімні рукави, які надають образу елегантності під час церемонії. Для вечора рукави можна зняти — й сукня перетвориться на лаконічну модель без бретелей, ідеальну для танців та святкування. Розріз додає сучасної сміливості, підкреслюючи стиль і легкість рухів.",
		},
	},
	{
		name: 'Estelle',
		id: 'estelle',
		category: 'Essence Collection',
		images: [
			'assets/photo/estelle/1.jpg',
			'assets/photo/estelle/2.jpg',
			'assets/photo/estelle/3.jpg',
			'assets/photo/estelle/4.jpg',
			'assets/photo/estelle/5.jpg',
			'assets/photo/estelle/6.jpg',
		],
		description: {
			en: 'Estelle is a floor-length gown with a soft neckline and a corset with back ties that beautifully defines the silhouette. Crafted from Chantilly lace layered with nylon, the dress has a light, airy texture with refined floral detailing.',
			ua: 'Estelle — сукня довжини максі з м’якою лінією декольте та корсетом зі шнурівкою на спинці, що гарно підкреслює силует. Виготовлена з мережива Chantilly, покритого нейлоном, сукня має легку, повітряну текстуру та вишукані квіткові деталі.',
		},
	},
	{
		name: 'Nicole',
		id: 'nicole',
		category: 'Signature Collection',
		images: [
			'assets/photo/nicole/1.jpg',
			'assets/photo/nicole/2.jpg',
			'assets/photo/nicole/3.jpg',
			'assets/photo/nicole/4.jpg',
			'assets/photo/nicole/5.jpg',
		],
		description: {
			en: "'Nicole' is a timeless and elegant gown with delicate thin straps. The bodice features soft draping and is beautifully embellished with pearls, adding a touch of sophistication. Fitted at the waist, the dress gently hugs the figure and flows smoothly down, creating a graceful silhouette.",
			ua: "'Nicole' — це вічна та елегантна сукня з тонкими бретелями. Верх оздоблений м’якими драпіруваннями та перлинами, що додає образу вишуканості. Сукня підкреслює талію, плавно облягає фігуру та м’яко спадає вниз, створюючи витончений силует.",
		},
	},
	{
		name: 'Naomi',
		id: 'naomi',
		category: 'Signature Collection',
		images: [
			'assets/photo/naomi/1.jpg',
			'assets/photo/naomi/2.jpg',
			'assets/photo/naomi/3.jpg',
			'assets/photo/naomi/4.jpg',
			'assets/photo/naomi/5.jpg',
		],
		description: {
			en: "The 'Naomi' dress is an elegant transformer wedding gown featuring a draped corset and modern versatility. It includes detachable sheer lace sleeves and a light tulle overskirt with a slit, layered over a sleek, straight-cut base dress. This design allows the bride to effortlessly transition from a refined ceremony look to a lighter, more relaxed style for the evening celebration.",
			ua: "Сукня 'Naomi' — елегантна весільна сукня-трансформер із драпірованим корсетом і сучасним підходом до стилю. У комплекті — знімні прозорі мереживні рукави та легка фатинова спідниця з розрізом, що одягається поверх прямої базової сукні. Ідеальне рішення для нареченої, яка хоче створити два образи — для офіційної церемонії та вечірки.",
		},
	},
	{
		name: 'Flora',
		id: 'flora',
		category: 'Signature Collection',
		images: [
			'assets/photo/flora/1.jpg',
			'assets/photo/flora/2.jpg',
			'assets/photo/flora/3.jpg',
			'assets/photo/flora/4.jpg',
			'assets/photo/flora/5.jpg',
		],
		description: {
			en: "The 'Flora' dress is a dreamy and romantic gown inspired by nature’s beauty. Delicate floral appliqués cascade down the bodice and skirt, creating a soft, ethereal look. The off-the-shoulder sleeves add a touch of elegance, while the structured corset ensures a flattering fit. With its airy tulle layers and intricate details, this dress is perfect for brides who want to embody grace and femininity.",
			ua: "Сукня 'Flora' — це мрійливий і романтичний образ, натхненний природною красою. Ніжні квіткові аплікації спадають уздовж ліфа та спідниці, створюючи легкий та чарівний ефект. Спущені рукави додають витонченості, а корсетний верх підкреслює фігуру. Легкі тюлеві шари та ретельно продумані деталі роблять цю сукню ідеальним вибором для наречених, які хочуть втілити ніжність і грацію.",
		},
	},
	{
		name: 'Bianca',
		id: 'bianca',
		category: 'Atelier Collection',
		images: [
			'assets/photo/bianca/1.jpg',
			'assets/photo/bianca/2.jpg',
			'assets/photo/bianca/3.jpg',
			'assets/photo/bianca/4.jpg',
			'assets/photo/bianca/5.jpg',
		],
		description: {
			en: "'Bianca' is an incredibly romantic gown featuring off-the-shoulder sleeves adorned with pearls. The bodice is also beautifully decorated with pearls and ties at the back, adding a soft, feminine charm to the overall look.",
			ua: "'Bianca' — неймовірно романтична сукня з відкритими плечима, оздобленими перлинами. Корсет також прикрашений перлами та зав’язується на спині, надаючи образу ніжності та жіночності.",
		},
	},
	{
		name: 'Cassandra',
		id: 'cassandra',
		category: 'Atelier Collection',
		images: [
			'assets/photo/cassandra/1.jpg',
			'assets/photo/cassandra/2.jpg',
			'assets/photo/cassandra/3.jpg',
			'assets/photo/cassandra/4.jpg',
		],
		description: {
			en: "The 'Cassandra' dress features a high neckline with intricate beading on a sheer bodice, creating a bold yet elegant look. The beaded bodice seamlessly transitions into a glossy, flowing skirt, which is accented by a thigh-high slit, adding a touch of allure to this shimmering gown.",
			ua: "Сукня 'Cassandra' має високий комір з витонченим бісером на прозорому ліфі, створюючи сміливий і водночас елегантний вигляд. Бісерний ліф плавно переходить у блискучу, струмливу спідницю, яка прикрашена високим розрізом, додаючи відтінок привабливості до цієї сукні.",
		},
	},
	{
		name: 'Elaine',
		id: 'elaine',
		category: 'Signature Collection',
		images: [
			'assets/photo/elaine/1.jpg',
			'assets/photo/elaine/2.jpg',
			'assets/photo/elaine/3.jpg',
			'assets/photo/elaine/4.jpg',
			'assets/photo/elaine/5.jpg',
		],
		description: {
			en: "'Elaine' is a timeless satin wedding gown that features a stunning one-shoulder draped sleeve, creating a sophisticated asymmetrical neckline. The soft pleating on the bodice highlights the waist and flows into a full A-line skirt with a daring thigh-high slit, adding both elegance and movement. The back of the dress reveals delicate satin ties that allow for an adjustable fit and add a touch of romantic charm. With its clean lines and unique silhouette, Elaine is designed for brides who want to make a graceful yet unforgettable entrance.",
			ua: "Сукня 'Elaine' — це вічна класика в сатиновому виконанні, яка зачаровує асиметричним вирізом з однією драпірованою бретеллю. М’які складки на ліфі підкреслюють талію й переходять у пишну спідницю з ефектним високим розрізом, додаючи образу витонченості та динаміки. Спинка прикрашена зав’язками зі сатину, які не тільки забезпечують зручну посадку, а й створюють романтичний акцент. Ідеальний вибір для наречених, які прагнуть виглядати елегантно та незабутньо.",
		},
	},
	{
		name: 'Ines',
		id: 'ines',
		category: 'Signature Collection',
		images: [
			'assets/photo/ines/1.jpg',
			'assets/photo/ines/2.jpg',
			'assets/photo/ines/3.jpg',
			'assets/photo/ines/4.jpg',
			'assets/photo/ines/5.jpg',
		],
		description: {
			en: "The 'Ines' dress is a sleek and modern gown with a touch of timeless elegance. Made from smooth, silky fabric, it drapes beautifully over the body, creating a flattering silhouette. The dress features a draped cowl neckline that adds softness and sophistication, while the thin spaghetti straps give it a delicate and feminine feel. A corset-style lace-up back ensures a perfect fit, and the high slit adds a bold yet graceful touch, allowing for effortless movement.",
			ua: "Сукня 'Ines' — це витончена та сучасна сукня з ноткою класичної елегантності. Виготовлена з гладкої шовковистої тканини, вона красиво облягає фігуру, створюючи витончений силует. Драпірований виріз додає ніжності та вишуканості, а тонкі бретелі надають легкості й жіночності. Корсетна шнурівка на спині забезпечує ідеальну посадку, а високий розріз додає сміливості та грації, дозволяючи вільно рухатися.",
		},
	},
	{
		name: 'Jasmine',
		id: 'jasmine',
		category: 'Atelier Collection',
		images: [
			'assets/photo/jasmine/1.jpg',
			'assets/photo/jasmine/2.jpg',
			'assets/photo/jasmine/3.jpg',
			'assets/photo/jasmine/4.jpg',
		],
		description: {
			en: "The 'Jasmine' dress boasts a chic halter neckline with soft pleats that flow into a full, graceful skirt. The waist is accentuated with a detailed, braided belt, adding texture and refinement. This timeless design also offers practicality with discreet side pockets, making it both stylish and functional.",
			ua: "Сукня 'Jasmine' має елегантний виріз халтер з ніжними складками, які плавно переходять у пишну, граціозну спідницю. Талія підкреслена деталізованим, плетеним поясом, що додає текстуру і вишуканість. Цей дизайн також пропонує практичність з прихованими кишенями з боків, роблячи сукню одночасно стильною та функціональною.",
		},
	},
	{
		name: 'Lily',
		id: 'lily',
		category: 'Atelier Collection',
		images: [
			'assets/photo/lily/1.jpg',
			'assets/photo/lily/2.jpg',
			'assets/photo/lily/3.jpg',
			'assets/photo/lily/4.jpg',
		],
		description: {
			en: "The 'Lily' dress features a delicate off-the-shoulder design with a sheer floral-embroidered corset and a back with a fastener for a secure fit. The soft tulle overlay adds an ethereal touch, while the fitted silhouette enhances its elegance and grace.",
			ua: "Сукня 'Lily' має ніжний дизайн з відкритими плечима та прозорим корсетом з квітковою вишивкою, а також спину з застібкою для надійної посадки. М'який тюлевий верх додає ефірного штриху, а приталений силует підкреслює елегантність і грацію.",
		},
	},
	{
		name: 'Linda',
		id: 'linda',
		category: 'Atelier Collection',
		images: [
			'assets/photo/linda/1.jpg',
			'assets/photo/linda/2.jpg',
			'assets/photo/linda/3.jpg',
			'assets/photo/linda/4.jpg',
			'assets/photo/linda/5.jpg',
		],
		description: {
			en: "'Linda' is a romantic and refined gown featuring a sheer bodice adorned with delicate lace that seamlessly flows into the skirt. The back is elegantly designed with a circular cut-out, accentuated by buttons above and below, adding a unique and graceful touch.",
			ua: "'Linda' — це романтична та витончена сукня з прозорим верхом, прикрашеним ніжним мереживом, яке плавно переходить у спідницю. Спинка оформлена круглим вирізом, доповненим гудзиками зверху та знизу, що додає образу оригінальності та елегантності.",
		},
	},
	{
		name: 'Madison',
		id: 'madison',
		category: 'Signature Collection',
		images: [
			'assets/photo/madison/1.jpg',
			'assets/photo/madison/2.jpg',
			'assets/photo/madison/3.jpg',
			'assets/photo/madison/4.jpg',
			'assets/photo/madison/5.jpg',
		],
		description: {
			en: "The 'Madison' dress is soft, romantic, and elegant. It has a flowy A-line shape with light tulle and pretty floral embroidery. The bodice features a sweetheart neckline with a sheer overlay and lace details. It also has long, sheer puff sleeves for a vintage touch. The back has a small open cut-out and delicate buttons. Perfect for a bride who wants a classic, fairytale look.",
			ua: "Сукня 'Madison' — ніжна, романтична й елегантна. Вона має легкий А-силует із повітряного тюлю та красивою вишивкою у вигляді квітів. Верх сукні прикрашений вирізом у формі серця з прозорою накидкою та мереживними деталями. Довгі прозорі рукави-ліхтарики додають вінтажного шарму. На спині — невеликий виріз і ніжні ґудзики. Ідеальний вибір для нареченої, яка мріє про класичний, казковий образ.",
		},
	},
	{
		name: 'Magnolia',
		id: 'magnolia',
		category: 'Signature Collection',
		images: [
			'assets/photo/magnolia/1.jpg',
			'assets/photo/magnolia/2.jpg',
			'assets/photo/magnolia/3.jpg',
			'assets/photo/magnolia/4.jpg',
			'assets/photo/magnolia/5.jpg',
		],
		description: {
			en: "The 'Magnolia' dress is an elegant gown with a romantic touch. It features a fitted bodice adorned with delicate lace and subtle beading for a hint of sparkle. Off-the-shoulder sleeves drape gracefully, complementing the smooth, flattering skirt. A detachable overskirt allows for a versatile look, adding volume or keeping it sleek.",
			ua: "Сукня 'Magnolia' – це елегантна сукня з романтичним акцентом. Вона має облягаючий корсет, прикрашений ніжним мереживом і витонченим бісером, що додає легкого сяйва. Спущені рукави красиво спадають, доповнюючи плавний, витончений силует. Знімна накидка додає універсальності образу, дозволяючи змінювати об’єм або залишати сукню більш приталеною.",
		},
	},
	{
		name: 'Pearl',
		id: 'pearl',
		category: 'Signature Collection',
		images: [
			'assets/photo/pearl/1.jpg',
			'assets/photo/pearl/2.jpg',
			'assets/photo/pearl/3.jpg',
			'assets/photo/pearl/4.jpg',
			'assets/photo/pearl/5.jpg',
		],
		description: {
			en: "The 'Pearl' dress is a timeless gown with graceful elegance. Made from smooth, flowing fabric, it drapes beautifully. The off-the-shoulder neckline and ruched bodice enhance the silhouette, while the full A-line skirt with a subtle slit adds charm and ease of movement. A lace-up back completes the classic look.",
			ua: "Сукня 'Pearl' — це вишукана та елегантна класика. Виготовлена з гладкої, легкої тканини, вона красиво лягає по фігурі. Відкритий виріз із драпіруванням і зібраний корсет підкреслюють силует, а пишна спідниця А-силуету з легким розрізом додає шарму та зручності. Шнурівка на спині завершує класичний образ.",
		},
	},
	{
		name: 'Sharon',
		id: 'sharon',
		category: 'Essence Collection',
		images: [
			'assets/photo/sharon/1.jpg',
			'assets/photo/sharon/2.jpg',
			'assets/photo/sharon/3.jpg',
			'assets/photo/sharon/4.jpg',
		],
		description: {
			en: 'Sharon features a structured corset with a deep neckline and a transparent back finished with a row of delicate buttons. The skirt softly follows the hips before flowing to the floor, creating a clean and confident silhouette. The dress is fully covered with high-quality lace, enriched with sequins and beads for a refined, luminous finish.',
			ua: 'Sharon — сукня зі структурованим корсетом, глибокою лінією декольте та прозорою спинкою, оздобленою рядом делікатних ґудзиків. Спідниця м’яко підкреслює стегна та плавно спадає донизу, формуючи чіткий і впевнений силует. Високоякісне мереживо з паєтками та бісером додає образу глибини й витонченого сяйва.',
		},
	},
	{
		name: 'Stacy',
		id: 'stacy',
		category: 'Atelier Collection',
		images: [
			'assets/photo/stacy/1.jpg',
			'assets/photo/stacy/2.jpg',
			'assets/photo/stacy/3.jpg',
			'assets/photo/stacy/4.jpg',
			'assets/photo/stacy/5.jpg',
		],
		description: {
			en: "The 'Stacy' dress is a bold and modern choice for the bride. This mini dress is covered in shimmering sequins and beads, with a sweetheart neckline and long sleeves. Its standout feature is a detachable tulle skirt that can be easily added for a more dramatic look. A perfect way to combine glamour and comfort.",
			ua: "Сукня 'Stacy' — яскравий і сучасний вибір для нареченої. Це міні-сукня, прикрашена блискучими паєтками та бісером, із вирізом у формі серця та довгими рукавами. Особливість сукні — знімна фатинова спідниця, яку можна легко прикріпити для більш урочистого образу. Ідеальний варіант, щоб поєднати розкіш і зручність.",
		},
	},
	{
		name: 'Sofi',
		id: 'sofi',
		category: 'Signature Collection',
		images: [
			'assets/photo/sofi/1.jpg',
			'assets/photo/sofi/2.jpg',
			'assets/photo/sofi/3.jpg',
			'assets/photo/sofi/4.jpg',
			'assets/photo/sofi/5.jpg',
		],
		description: {
			en: "'Sofi' is a delicate and graceful gown with thin straps and a bodice adorned with 3D floral lace that softly flows into a light tulle skirt. The deep, elegant back neckline adds a touch of allure. A truly fairytale dress for a modern princess.",
			ua: "'Sofi' — ніжна та витончена сукня з тонкими бретельками. Верх оздоблений об’ємним мереживом із 3D-квітами, яке плавно переходить у легку фатинову спідницю. Глибокий, елегантний виріз на спинці додає шарму. Сукня справжньої принцеси.",
		},
	},
	{
		name: 'Valerie',
		id: 'valerie',
		category: 'Essence Collection',
		images: [
			'assets/photo/valerie/1.jpg',
			'assets/photo/valerie/2.jpg',
			'assets/photo/valerie/3.jpg',
			'assets/photo/valerie/4.jpg',
			'assets/photo/valerie/5.jpg',
			'assets/photo/valerie/6.jpg',
			'assets/photo/valerie/7.jpg',
		],
		description: {
			en: 'Valerie features a defined neckline and a fully lace-covered silhouette with floral and leaf motifs, finished with subtle sequins. Back lacing allows the waist to be elegantly shaped. The set includes shoulder-length gloves, with the option to add a chiffon scarf for a more layered look.',
			ua: 'Valerie — сукня з виразною лінією декольте та повністю мереживним силуетом з візерунками квітів і листя, доповненими делікатними паєтками. Шнурівка на спинці дозволяє красиво підкреслити талію. У комплект входять рукавички до плечей, а за бажанням образ можна доповнити шифоновим шарфом.',
		},
	},
	{
		name: 'Susanna',
		id: 'susanna',
		category: 'Signature Collection',
		images: [
			'assets/photo/susanna/1.jpg',
			'assets/photo/susanna/2.jpg',
			'assets/photo/susanna/3.jpg',
			'assets/photo/susanna/4.jpg',
			'assets/photo/susanna/5.jpg',
		],
		description: {
			en: "The 'Susanna' dress is a romantic A-line wedding gown with a fitted bodice and a light tulle skirt. Delicate floral lace gracefully adorns the bodice and flows onto the skirt, adding elegance. A deep neckline with wide straps, an open back, and a high slit in the skirt create a modern yet refined look. The long train adds a touch of fairytale charm.",
			ua: "Сукня 'Susanna' — це романтична весільна сукня А-силуету з облягаючим корсетом і легкою фатиновою спідницею. Квіткове мереживо витончено прикрашає корсет і переходить на спідницю, додаючи елегантності. Глибоке декольте з широкими бретелями, відкрита спина та високий розріз на спідниці створюють сучасний і водночас вишуканий образ. Довгий шлейф додає казкової грації.",
		},
	},
];
